import type { Work } from './types'

/** Order = order on the home page and the works page. */
export const works: Work[] = [
  {
    slug: "sienna",
    title: "Sienna",
    services: ["Web design","Branding","Framer development"],
    cover: { src: "/images/works/sienna-cover.png", alt: "Sienna", width: 1600, height: 1200 },
    hoverCover: { src: "/images/works/sienna-1.jpg", alt: "Sienna", width: 1600, height: 1200 },
    description: "Sienna is a premium Framer template designed for photographers and freelancers who want a stunning online presence without any coding or design skills.",
    overview: "Showcase your talent with Sienna – a refined Framer template crafted for photographers and freelancers. With a sleek, modern layout, it highlights your portfolio, services, and client stories, ensuring your work stands out effortlessly.",
    date: "November 18, 2025",
    client: "Sienna",
    industry: "Photography Portfolio",
    gallery: [{ src: "/images/works/sienna-1.jpg", alt: "Sienna", width: 1600, height: 1200 }, { src: "/images/works/sienna-2.png", alt: "Sienna", width: 1600, height: 1200 }, { src: "/images/works/sienna-3.png", alt: "Sienna", width: 1600, height: 1200 }, { src: "/images/works/sienna-4.png", alt: "Sienna", width: 1600, height: 1200 }],
  },
  {
    slug: "glidex",
    title: "Glidex",
    services: ["Web design","Branding","SEO"],
    cover: { src: "/images/works/glidex-cover.png", alt: "Glidex", width: 1600, height: 1200 },
    hoverCover: { src: "/images/works/glidex-1.png", alt: "Glidex", width: 1600, height: 1200 },
    description: "A sleek template for video producers and filmmakers to showcase their work.",
    overview: "Glidex is a modern and dynamic template for video producers and filmmakers, featuring a stylish bento layout that organizes your portfolio into sleek, manageable sections. With its perfect 100 score on PageSpeed Insights, Glidex ensures lightning-fast performance and a seamless user experience, making it the ideal choice for showcasing your creative work with impact and efficiency.",
    date: "November 18, 2025",
    client: "Ama Jean - Marketing lead at Glidex",
    industry: "Videography Production Studio",
    gallery: [{ src: "/images/works/glidex-1.png", alt: "Glidex", width: 1600, height: 1200 }, { src: "/images/works/glidex-2.png", alt: "Glidex", width: 1600, height: 1200 }, { src: "/images/works/glidex-3.png", alt: "Glidex", width: 1600, height: 1200 }, { src: "/images/works/glidex-cover.png", alt: "Glidex", width: 1600, height: 1200 }],
  },
  {
    slug: "veon",
    title: "Veon",
    services: ["E-Commerce","UIUX Design","Shopify","Framer Development"],
    cover: { src: "/images/works/veon-cover.png", alt: "Veon", width: 1600, height: 1200 },
    hoverCover: { src: "/images/works/veon-1.png", alt: "Veon", width: 1600, height: 1200 },
    description: "Veon is a high-quality, minimalist Framer template designed for clothing brands and e-commerce businesses.",
    overview: "With seamless Shopify integration via Framercommerce, it’s optimized for speed, conversions, and an effortless shopping experience.",
    date: "November 18, 2025",
    client: "Fabian Clark - CO at Veon",
    industry: "Fashion E-Commerce Store",
    gallery: [{ src: "/images/works/veon-1.png", alt: "Veon", width: 1600, height: 1200 }, { src: "/images/works/veon-2.png", alt: "Veon", width: 1600, height: 1200 }, { src: "/images/works/veon-3.png", alt: "Veon", width: 1600, height: 1200 }, { src: "/images/works/veon-4.png", alt: "Veon", width: 1600, height: 1200 }],
  },
  {
    slug: "zayla",
    title: "Zayla",
    services: ["Web Development","Content Creation"],
    cover: { src: "/images/works/zayla-cover.png", alt: "Zayla", width: 1600, height: 1200 },
    hoverCover: { src: "/images/works/zayla-1.png", alt: "Zayla", width: 1600, height: 1200 },
    description: "A striking and modern Framer template made for independent creatives, developers, artists, and visionaries who want to leave a powerful first impression.",
    overview: "Zayla is a dramatic yet refined Framer template designed for those who embrace bold visuals and high-impact storytelling. Whether you’re a creative designer, digital artist, innovative developer, or any professional craving a daring web presence, this versatile portfolio template empowers you to showcase your talent with style and confidence.",
    date: "November 18, 2025",
    client: "Zayla Monroe",
    industry: "Personal Animated Graphic Design",
    liveUrl: "https://zaylamonroe.framer.website/",
    gallery: [{ src: "/images/works/zayla-1.png", alt: "Zayla", width: 1600, height: 1200 }, { src: "/images/works/zayla-2.png", alt: "Zayla", width: 1600, height: 1200 }, { src: "/images/works/zayla-3.png", alt: "Zayla", width: 1600, height: 1200 }, { src: "/images/works/zayla-4.png", alt: "Zayla", width: 1600, height: 1200 }],
  },
  {
    slug: "destello",
    title: "Destello",
    services: ["UIUX Design","Branding","Framer Development","AI Automation"],
    cover: { src: "/images/works/destello-cover.png", alt: "Destello", width: 1600, height: 1200 },
    hoverCover: { src: "/images/works/destello-1.png", alt: "Destello", width: 1600, height: 1200 },
    description: "Destello is a modern Framer Studio template built for professionals who value minimalism and clarity.",
    overview: "Destello is a modern Framer Studio template built for professionals who value minimalism and clarity. With a clean grid, elegant typography, and smooth subtle motion, it helps you present your work in a way that feels both refined and approachable. Ideal for designers, developers, and studios seeking a sleek online presence.",
    date: "November 18, 2025",
    client: "Maya L - Director at Destello",
    industry: "Agency Editorial",
    liveUrl: "https://destello.framer.website/",
    gallery: [{ src: "/images/works/destello-1.png", alt: "Destello", width: 1600, height: 1200 }, { src: "/images/works/destello-2.png", alt: "Destello", width: 1600, height: 1200 }, { src: "/images/works/destello-3.png", alt: "Destello", width: 1600, height: 1200 }, { src: "/images/works/destello-4.png", alt: "Destello", width: 2568, height: 2962 }],
  },
]

export const getWork = (slug: string) => works.find((w) => w.slug === slug)
export const nextWork = (slug: string) => works[(works.findIndex((w) => w.slug === slug) + 1) % works.length]
