/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    works: Work;
    posts: Post;
    media: Media;
    services: Service;
    testimonials: Testimonial;
    clients: Client;
    awards: Award;
    faqs: Faq;
    messages: Message;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    works: WorksSelect<false> | WorksSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    pages: Page;
    site: Site;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The home page shows the five works whose slugs match the template layout — sienna, glidex, veon, zayla, destello — each in its own hand-placed cell. Dragging to reorder here only changes the /works page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * URL segment: /works/<slug>
   */
  slug: string;
  date?: string | null;
  /**
   * Card image (4:3).
   */
  cover: number | Media;
  /**
   * Revealed by the liquid hover effect on cards. Defaults to the first gallery image.
   */
  hoverCover?: (number | null) | Media;
  /**
   * One-liner shown next to the title on the case-study page.
   */
  description?: string | null;
  /**
   * Overview paragraph on the case-study page.
   */
  overview?: string | null;
  client?: string | null;
  industry?: string | null;
  liveUrl?: string | null;
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Four images shown in a 2×2 grid.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * URL segment: /blogs/<slug>
   */
  slug: string;
  /**
   * Show on the home page (the first three featured posts are used).
   */
  featured?: boolean | null;
  date: string;
  /**
   * Shown as the card eyebrow, e.g. "Design Strategy".
   */
  category: string;
  cover: number | Media;
  /**
   * Use Heading 3 for section titles; paragraphs and bullet lists are supported.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  /**
   * Service row title, e.g. "Website Design & Development".
   */
  title: string;
  /**
   * Service row description.
   */
  text?: string | null;
  /**
   * Small pill tags shown on the service row (e.g. "Figma", "Framer").
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Image revealed on hover for this service row.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  /**
   * The quote, shown in the testimonial card.
   */
  quote: string;
  /**
   * Person’s name, shown under the quote.
   */
  name: string;
  /**
   * Person’s role and company, e.g. "Director, Aestha Studio".
   */
  role?: string | null;
  /**
   * Small photo shown next to the name.
   */
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  _order?: string | null;
  /**
   * Client name, shown under the logo.
   */
  name: string;
  /**
   * Year worked with, e.g. "2025".
   */
  year?: string | null;
  /**
   * Client logo image.
   */
  image?: (number | null) | Media;
  /**
   * Optional link the client card opens (leave empty for none).
   */
  href?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  _order?: string | null;
  /**
   * Award name, e.g. "Awwwards (3×)".
   */
  name: string;
  /**
   * Short description of the award.
   */
  text?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  /**
   * The question, shown as the accordion row.
   */
  question: string;
  /**
   * The answer, shown when the row is expanded.
   */
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  budget?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  date?: T;
  cover?: T;
  hoverCover?: T;
  description?: T;
  overview?: T;
  client?: T;
  industry?: T;
  liveUrl?: T;
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  featured?: T;
  date?: T;
  category?: T;
  cover?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  text?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  quote?: T;
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  year?: T;
  image?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  budget?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page hero — the paragraph under the big name.
     */
    intro?: string | null;
    /**
     * Home page hero — the four label/value stats under the intro (e.g. Location — London, UK).
     */
    bio?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Home page About section — the intro paragraphs next to the photo.
     */
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Home page About section — the tall portrait photo.
     */
    image1?: (number | null) | Media;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page About section — the caption next to the second photo.
     */
    caption?: string | null;
    /**
     * Home page About section — the wide photo next to the caption.
     */
    image2?: (number | null) | Media;
    /**
     * Home page About section — small label above "Driven Result" heading.
     */
    resultTag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page About section — heading above the metrics row.
     */
    resultHeading?: string | null;
    /**
     * Home page About section — up to four count-up stats (position = dot number).
     */
    metrics?:
      | {
          /**
           * e.g. 62
           */
          end: number;
          /**
           * e.g. "+" or "%".
           */
          suffix?: string | null;
          /**
           * e.g. "Projects".
           */
          label: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The Showcase section is an interactive demo app that explodes into its five layers as you scroll. Everything but the app’s name is built in code — the layer labels are not editable.
   */
  showcase?: {
    /**
     * Home page Showcase — the name shown in the demo app’s sidebar (e.g. "Ledger").
     */
    appName?: string | null;
  };
  works?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Works section heading.
     */
    heading?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Works section — paragraph under the heading.
     */
    text?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Works section — closing paragraph before the button.
     */
    outro?: string | null;
    /**
     * Home page Works section — "Explore all works" button label.
     */
    cta?: string | null;
  };
  services?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Services section heading.
     */
    heading?: string | null;
    /**
     * Home page Services section — paragraph under the heading.
     */
    text?: string | null;
    /**
     * Home page Services section — first side photo.
     */
    image1?: (number | null) | Media;
    /**
     * Home page Services section — second side photo. Rows themselves are edited in the Services list.
     */
    image2?: (number | null) | Media;
  };
  testimonials?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Testimonials section heading.
     */
    heading?: string | null;
    /**
     * Home page Testimonials — "previous" slider button label.
     */
    prev?: string | null;
    /**
     * Home page Testimonials — "next" slider button label.
     */
    next?: string | null;
  };
  clients?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Clients section heading.
     */
    heading?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Clients section — paragraph under the heading.
     */
    text?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Clients section — sentence above the "Book a call" button.
     */
    sentence?: string | null;
    /**
     * Home page Clients section — "Book a call" button label.
     */
    cta?: string | null;
  };
  approach?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Approach section heading.
     */
    heading?: string | null;
    /**
     * Home page Approach section — paragraph under the heading.
     */
    text?: string | null;
    /**
     * Home page Approach section photo.
     */
    image?: (number | null) | Media;
    /**
     * Home page Approach section — up to four process steps (position = dot number).
     */
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  awards?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Awards section heading.
     */
    heading?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Awards section — sentence under the heading. Awards themselves are edited in the Awards list.
     */
    sentence?: string | null;
  };
  blogs?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Blogs section heading.
     */
    heading?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Blogs section — text next to the author avatar.
     */
    profileText?: string | null;
    /**
     * Home page Blogs section — "Read more blogs" button label.
     */
    cta?: string | null;
  };
  faq?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page FAQ section heading.
     */
    heading?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page FAQ section — "Didn’t find your answer?" heading.
     */
    outroHeading?: string | null;
    /**
     * Home page FAQ section — paragraph under the outro heading.
     */
    outroText?: string | null;
    /**
     * Home page FAQ section — "Send me a message" button label.
     */
    outroCta?: string | null;
  };
  contact?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Contact section heading.
     */
    heading?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Contact section — sentence under the heading.
     */
    sentence?: string | null;
    /**
     * Home page Contact section — small "Let’s Connect" label.
     */
    connectLabel?: string | null;
    /**
     * Home page Contact section — the form fields, in order.
     */
    fields?:
      | {
          /**
           * Which form value this row is — the label below is what visitors see
           */
          key: 'Name' | 'Email' | 'Phone' | 'Budget' | 'Message';
          /**
           * Field label, e.g. "Name".
           */
          name: string;
          placeholder?: string | null;
          type?: ('text' | 'email' | 'tel' | 'textarea') | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Home page Contact section — "I usually reply within 24 hours" note.
     */
    replyNote?: string | null;
    /**
     * Contact form — submit button default label.
     */
    submit?: string | null;
    /**
     * Contact form — submit button label while sending.
     */
    submitting?: string | null;
    /**
     * Contact form — submit button label after a successful send.
     */
    sent?: string | null;
    /**
     * Contact form — submit button label after a failed send.
     */
    failed?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  notFound?: {
    /**
     * 404 page — big heading (e.g. "404").
     */
    heading?: string | null;
    /**
     * 404 page — explanation paragraph.
     */
    text?: string | null;
    /**
     * 404 page — "Back to Home" button label.
     */
    cta?: string | null;
  };
  works?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Works page (/works) — heading at the top.
     */
    heading?: string | null;
    /**
     * Works page (/works) — paragraph under the heading.
     */
    text?: string | null;
  };
  blogs?: {
    /**
     * Small mono label above the heading, e.g. "Services(04)".
     */
    tag?: string | null;
    /**
     * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Blogs page (/blogs) — heading at the top.
     */
    heading?: string | null;
    /**
     * Blogs page (/blogs) — paragraph under the heading.
     */
    text?: string | null;
  };
  workLabels?: {
    /**
     * Work case-study page — "Overview" section label.
     */
    overview?: string | null;
    /**
     * Work case-study page — "Date:" label.
     */
    date?: string | null;
    /**
     * Work case-study page — "Client:" label.
     */
    client?: string | null;
    /**
     * Work case-study page — "Industry:" label.
     */
    industry?: string | null;
    /**
     * Work case-study page — "Services:" label.
     */
    services?: string | null;
    /**
     * Work case-study page — "Live Project:" label.
     */
    live?: string | null;
    /**
     * Work case-study page — "Next Project" heading.
     */
    next?: string | null;
    /**
     * Work case-study page — "Explore all works" button label.
     */
    cta?: string | null;
  };
  blogLabels?: {
    /**
     * Blog post page — "Next Blogs" heading.
     */
    next?: string | null;
    /**
     * Blog post page — "Explore all blogs" button label.
     */
    cta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  /**
   * Used in titles, the preloader and the giant footer wordmark.
   */
  name: string;
  /**
   * Logo, first line
   */
  wordmarkLine1: string;
  /**
   * Logo, second line
   */
  wordmarkLine2: string;
  /**
   * Default meta description / Open Graph description.
   */
  description: string;
  ogImage?: (number | null) | Media;
  hero?: {
    /**
     * Full-bleed photo behind the wordmarks (2400×1412 in the template).
     */
    image?: (number | null) | Media;
    /**
     * e.g. Elian
     */
    nameLine1?: string | null;
    /**
     * e.g. Kent
     */
    nameLine2?: string | null;
    /**
     * Small cell bottom-left, e.g. "Building the future of email at Resend."
     */
    badge?: string | null;
  };
  /**
   * Header + footer sitemap. Use "/#about" style links for home sections.
   */
  nav?:
    | {
        label: string;
        to: string;
        id?: string | null;
      }[]
    | null;
  bookCall: {
    label: string;
    href: string;
    id?: string | null;
  };
  contact: {
    email: string;
    phone: string;
  };
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The small avatar + name + role shown in Clients, Blogs and Contact.
   */
  profile: {
    name: string;
    role: string;
    avatar?: (number | null) | Media;
  };
  /**
   * Grey by default. Wrap the white part in **double asterisks**. Enter = new line. Footer — the tagline sentence above the social links.
   */
  tagline?: string | null;
  socialsTitle?: string | null;
  socialsText?: string | null;
  createdBy?: {
    label?: string | null;
    name?: string | null;
    href?: string | null;
    avatar?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        intro?: T;
        bio?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        tag?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image1?: T;
        caption?: T;
        image2?: T;
        resultTag?: T;
        resultHeading?: T;
        metrics?:
          | T
          | {
              end?: T;
              suffix?: T;
              label?: T;
              text?: T;
              id?: T;
            };
      };
  showcase?:
    | T
    | {
        appName?: T;
      };
  works?:
    | T
    | {
        tag?: T;
        heading?: T;
        text?: T;
        outro?: T;
        cta?: T;
      };
  services?:
    | T
    | {
        tag?: T;
        heading?: T;
        text?: T;
        image1?: T;
        image2?: T;
      };
  testimonials?:
    | T
    | {
        tag?: T;
        heading?: T;
        prev?: T;
        next?: T;
      };
  clients?:
    | T
    | {
        tag?: T;
        heading?: T;
        text?: T;
        sentence?: T;
        cta?: T;
      };
  approach?:
    | T
    | {
        tag?: T;
        heading?: T;
        text?: T;
        image?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  awards?:
    | T
    | {
        tag?: T;
        heading?: T;
        sentence?: T;
      };
  blogs?:
    | T
    | {
        tag?: T;
        heading?: T;
        profileText?: T;
        cta?: T;
      };
  faq?:
    | T
    | {
        tag?: T;
        heading?: T;
        outroHeading?: T;
        outroText?: T;
        outroCta?: T;
      };
  contact?:
    | T
    | {
        tag?: T;
        heading?: T;
        sentence?: T;
        connectLabel?: T;
        fields?:
          | T
          | {
              key?: T;
              name?: T;
              placeholder?: T;
              type?: T;
              id?: T;
            };
        replyNote?: T;
        submit?: T;
        submitting?: T;
        sent?: T;
        failed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  notFound?:
    | T
    | {
        heading?: T;
        text?: T;
        cta?: T;
      };
  works?:
    | T
    | {
        tag?: T;
        heading?: T;
        text?: T;
      };
  blogs?:
    | T
    | {
        tag?: T;
        heading?: T;
        text?: T;
      };
  workLabels?:
    | T
    | {
        overview?: T;
        date?: T;
        client?: T;
        industry?: T;
        services?: T;
        live?: T;
        next?: T;
        cta?: T;
      };
  blogLabels?:
    | T
    | {
        next?: T;
        cta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  wordmarkLine1?: T;
  wordmarkLine2?: T;
  description?: T;
  ogImage?: T;
  hero?:
    | T
    | {
        image?: T;
        nameLine1?: T;
        nameLine2?: T;
        badge?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        to?: T;
        id?: T;
      };
  bookCall?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  profile?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
      };
  tagline?: T;
  socialsTitle?: T;
  socialsText?: T;
  createdBy?:
    | T
    | {
        label?: T;
        name?: T;
        href?: T;
        avatar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}